### PR TITLE
PEP8

### PR DESCRIPTION
**Pull request by Cabalist**
This comes AFTER and INCLUDES my previous pull request.

Here are a number of PEP8 fixes for the code.    Each commit addresses one thing.  

These should be familiar from the plotink series of patches.   I have a couple questions about this that I will delay for another patch set.  I wanted to make sure this one was specifically PEP8 (and one small bug in 1a2817c).

### CODE REVIEW

**Comment by oskay** [comment]
Would you be willing to try again, pulling against the current version (post tab->space) change? It's hard to see when every line is still showing changes.

**Comment by Cabalist** [comment]
It should be updated now.

**Comment by oskay** [comment]
Thank you.

**Comment by oskay** [comment]
I've started (but not finished) looking at this.
* The docstring starting at line 2087 should mostly be left alone. This is not code, and these changes do not increase clarity. I've pushed a commit to this effect.

* I would strongly prefer to _not_ change any of the self.options._xxxx_ variable names, unless there is a sufficient and specific cause to do so for that specific variable. These are the option argument names, and changing them here would require that they are simultaneously updated in other files (including some in other repositories). Changing any CLI argument name will (at least temporarily) break someone's workflow, and we should weigh any specific change against that. I will start going through these so that the code can head towards testing.

Unrelated:
* What is "noinspection PyCompatibility"? I imagine that this is an artifact of some inspection tool that you're using.

**Comment by oskay** [comment]
It looks like the option parameters are 50/50 renamed or not. I'll try to make this consistent. 
Also, I hadn't realized that the option parser hadn't been updated at all-- if we only update how it stores the variables, then it shouldn't break the input parser options.

**Comment by oskay** [comment]
With last commit, code appears to at work, to the limits of my basic testing. Took a while to read through everything.

Excellent catch on one excessively-indented section there. I never would have seen that. :)

Looks like we're good to go.

**Comment by Cabalist** [comment]
> The docstring starting at line 2087 should mostly be left alone. This is not code, and these changes do not increase clarity. I've pushed a commit to this effect.

Agreed and noted.  I'll keep this in mind in the future.  

> What is "noinspection PyCompatibility"? I imagine that this is an artifact of some inspection tool that you're using.

Bingo.  Didn't realize that made it in there.  It keeps my linter from squawking about Py2/3 incompatibilities on that piece of code that will always only work on one or the other.  

> option parameters

I try very hard not to alter any of the API for the this code as I don't know what is up or downstream.  The changes you made for consistency make sense.  

This code is fun and challenging to read and I appreciate your responsiveness to pull requests.  :)

**Comment by oskay** [comment]
Thank you for putting the time into this!

**Pull request merged**
