### PR TITLE
Remove Python2 cruft

### PR DESCRIPTION
**Pull request by alexrudd2**
Using `pyupgrade` (via the excellent `ruff`), I found some junk remaining from earlier Python versions.

- Replace deprecated `mock` with [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html) (available since `3.3`)
- Remove unnecessary UTF-8 encoding (unnecessary since Python 3, [PEP3120](https://peps.python.org/pep-3120/))
- Remove python2 print_function (unnecessary since Python 3)
- Remove unneeded arguments from `super()` (unnecessary since Python 3)
- Change `IOError` to `OSError` ([aliased](https://docs.python.org/3/library/exceptions.html#IOError) in Python 3.3)
- Remove unnecessary `()` after class definitions ([docs](https://docs.python.org/3/tutorial/classes.html#class-objects))
- Remove old string encoding code (from Python2).  For bonus points, fix the `lstrip()` function

### CODE REVIEW

**Comment by oskay** [comment]
Thanks for this; I agree with most of these changes, but -- since there are quite a lot -- I'll need to review them a bit more. I'm also planning to pull in the minor changes from this week's bug fix release (3.9.2) first.

**Comment by oskay** [comment]
test_axidraw_cli.py is failing with these changes on Python 3.7, but passing on 3.8, 3.9, 3.10, and 3.11.  I'll have to look into this further.

**Comment by alexrudd2** [comment]
> test_axidraw_cli.py is failing with these changes on Python 3.7, but passing on 3.8, 3.9, 3.10, and 3.11. I'll have to look into this further.

Hmm, how do you have the tests setup?  I tried running `pytest` locally but couldn't install `axidrawinternal`.  Is that package on some private registry?

**Comment by oskay** [comment]
> Hmm, how do you have the tests setup? I tried running `pytest` locally but couldn't install `axidrawinternal`. Is that package on some private registry?

The package is [in releases](https://github.com/evil-mad/axidraw/releases/tag/v3.9.0): [AxiDraw_API_390.zip](https://github.com/evil-mad/axidraw/releases/download/v3.9.0/AxiDraw_API_390.zip) 

If you install that via pip, you can replace individual files in axidrawinternal.

**Comment by alexrudd2** [comment]
> > Hmm, how do you have the tests setup? I tried running `pytest` locally but couldn't install `axidrawinternal`. Is that package on some private registry?
> 
> The package is [in releases](https://github.com/evil-mad/axidraw/releases/tag/v3.9.0): [AxiDraw_API_390.zip](https://github.com/evil-mad/axidraw/releases/download/v3.9.0/AxiDraw_API_390.zip)
> 
> If you install that via pip, you can replace individual files in axidrawinternal.

OK, thank you!  `pip install https://github.com/evil-mad/axidraw/releases/download/v3.9.0/AxiDraw_API_390.zip` worked fine.  Now I can't figure out your test scheme for the life of me.  :)

I read all of `installation.txt`, `setup.py`, `README.txt`, and `pyproject.toml`, but they don't say anything.
 `axidraw/cli/test/testsmoke.py` seemed to offer a clue:
> `# python -m unittest discover -s test in top-level package dir`

Running this in `axidraw` or `axidraw/inkscape driver` appears to try and run thousands of tests with all sorts of errors and doesn't end for several minutes.  Running it in `axidraw/cli` gives:
```
ERROR: test_load_config (test_axicli.test_utils.UtilsTestCase.test_load_config) (filename='test/assets/conf_without_suffix')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/a.ruddick/Documents/github/axidraw/cli/axicli/utils.py", line 90, in load_config
    config_dict = runpy.run_path(config)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 290, in run_path
  File "<frozen runpy>", line 254, in _get_code_from_file
FileNotFoundError: [Errno 2] No such file or directory: '/Users/a.ruddick/Documents/github/axidraw/cli/test/assets/conf_without_suffix'
----------------------------------------------------------------------
Ran 16 tests in 0.255s

FAILED (errors=2)
```

**Comment by alexrudd2** [comment]
`pytest` seems to do a bit better.  In `axidraw/cli`
```
------------------------------------ Captured stdout call -------------------------------------
Could not find any file named test/assets/hta_custom_config.py.
Check the spelling and/or location.
=================================== short test summary info ===================================
FAILED test/test_axicli/test_utils.py::UtilsTestCase::test_load_config - SystemExit: 1
================================ 1 failed, 15 passed in 0.43s =================================
```

OK, sure there is no file `hta_custom_config.py`.  I changed the test to 
```python
    def test_load_config(self):
        config_filenames = ["test/assets/axidraw_conf.py"]
```
and got a little farther.

Adding `font_option = "EMSAllure"` to `axidraw_conf.py` makes the tests pass.  (Python 3.11 on an M1 Mac)

**Comment by oskay** [comment]
Again, I'm only seeing failures on Python 3.7.

**Comment by alexrudd2** [comment]
> Again, I'm only seeing failures on Python 3.7.

Yes, I'm trying to get the tests running locally first (on my default 3.11), and then go back and install 3.7.  `brew` refuses to install 3.7, though, so my next option is to setup CI on GitHub Actions, I think.

However, 3.7 just [reached End-of-Life](https://github.com/evil-mad/axidraw/pull/155#issuecomment-1615205675) a few days ago, so perhaps it's better to drop it altogether?

**Comment by alexrudd2** [comment]
Also, it is possible your development environment has changes that aren't committed to git?  My above comments refer to the difficulties running `pytest` on a fresh `git clone`.  I'm happy to submit a PR to improve that, just need to figure out your intended way of running tests.

Thanks again for the help.

**Comment by oskay** [comment]
Sorry for the extra test in there; that's unrelated to the other parts here.

**Comment by oskay** [comment]
I am aware that Python 3.7 is at end of life. I have apologized for the extra test in there, and did just push a commit to remove it.

My main development environment is Python 3.11 on an M1 Mac, with the software installed via pip the same way that you did. I have a CI server that is running tests on 3.7, 3.8, 3.9, 3.10, and 3.11, and it is only showing the error on 3.7.

There *were* a number of changes in unittest.mock in 3.8, and so I'd say that pyupgrade may be *a little too eager* to make that one particular change. It is probably worth setting this change aside until we are ready to drop 3.7.

**Comment by alexrudd2** [comment]
> I am aware that Python 3.7 is at end of life. I have apologized for the extra test in there, and did just push a commit to remove it.

Yes, I saw that.  (I had changed the test rather than removing it).

> There _were_ a number of changes in unittest.mock in 3.8, and so I'd say that pyupgrade may be _a little too eager_ to make that one particular change. It is probably worth setting this change aside until we are ready to drop 3.7.

Fair enough!  It's your code :)

> My main development environment is Python 3.11 on an M1 Mac, with the software installed via pip the same way that you did. I have a CI server that is running tests on 3.7, 3.8, 3.9, 3.10, and 3.11, and it is only showing the error on 3.7.

Are you interested in setting up GitHub Actions?  I have it running on [my fork](https://github.com/alexrudd2/axidraw/pull/2/checks) and can just submit that same PR here.

**Comment by alexrudd2** [comment]
> There _were_ a number of changes in unittest.mock in 3.8, and so I'd say that pyupgrade may be _a little too eager_ to make that one particular change. It is probably worth setting this change aside until we are ready to drop 3.7.

You were right, it was the `mock` changes.  I believe the default pyupgrade config uses Python3.8, and I should have changed it to 3.7.  I'm going to close this PR in favor of one that's cleaned up.

**Comment by oskay** [comment]
It looks as though this can be made to pass by undoing
(1) the change to pyproject.toml (leaving mock in) and
(2) the import change to  test_axidraw_cli.py

If you approve, I'll commit to this PR making those two changes.

**Comment by oskay** [comment]
Looks like you've got the new one in; I'll drop this.

**Comment by alexrudd2** [comment]
> It looks as though this can be made to pass by undoing (1) the change to pyproject.toml (leaving mock in) and (2) the import change to test_axidraw_cli.py
> 
> If you approve, I'll commit to this PR making those two changes.

Yes, I agree.  

I recreated the PR as https://github.com/evil-mad/axidraw/pull/158, fixing the test instead of deleting it and dropping all the `mock` changes.

**Pull request closed without merging**
