### PR TITLE
Speed up plot_optimizations.reorder() with Hilbert Curve

### PR DESCRIPTION
**Pull request by migurski**
Follow-up to https://github.com/evil-mad/axidraw/pull/112 speeding up `plot_optimizations.reorder()` for the same reasons.

This pull request introduces a spatial index to reduce needed comparisons with a parameter to trade off time and distance savings. I’ve included some initial results with time improvement over unoptimized and a comparison of pen-up distance reduction after reordering over unoptimized.

The pen-up distance improvements with optimization are generally comparable when `CURVE_DISTANCE = 100` but 80-90% faster to find. These time improvement are a bit less dramatic than the last PR but still meaningful.

The [Hilbert Curve library](https://pypi.org/project/hilbertcurve/) has NumPy as an expensive dependency, so it may be worth trying to port if this approach makes sense.

<table>
<tr>
<th>File</th><th>Paths</th><th><tt>CURVE_DISTANCE</tt></th><th>Time before #113</th><th>Distance savings before #113</th><th>Time after #113</th><th>Distance savings after #113</th><th>Time Improvement</th>
</tr>

<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-10-slateblue.svg">stroke-10-slateblue.svg</a></td><td>1</td><td>5</td><td>0.00 sec</td><td>0%</td><td>0.00 sec</td><td>—</td><td>—</td>
</tr>

<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-8-mediumblue.svg">stroke-8-mediumblue.svg</a></td><td>2,118</td><td>5</td><td>1.72 sec</td><td>88%</td><td>0.12 sec</td><td>64%</td><td>93%</td>
</tr>
<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-8-mediumblue.svg">stroke-8-mediumblue.svg</a></td><td>2,118 (reverse)</td><td>5</td><td>3.24 sec</td><td>95%</td><td>0.13 sec</td><td>63%</td><td>96%</td>
</tr>
<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-10-slateblue.svg">stroke-10-slateblue.svg</a></td><td>1</td><td>100</td><td>0.00 sec</td><td>0%</td><td>0.00 sec</td><td>—</td><td>—</td>
</tr>
<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-11-navy.svg">stroke-11-navy.svg</a></td><td>3,424</td><td>100</td><td>4.63 sec</td><td>90%</td><td>0.52 sec</td><td>88%</td><td>89%</td>
</tr>
<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-11-navy.svg">stroke-11-navy.svg</a></td><td>3,424 (reverse)</td><td>100</td><td>9.07 sec</td><td>96%</td><td>0.68 sec</td><td>91%</td><td>93%</td>
</tr>
<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-8-mediumblue.svg">stroke-8-mediumblue.svg</a></td><td>2,118</td><td>100</td><td>1.72 sec</td><td>88%</td><td>0.32 sec</td><td>85%</td><td>81%</td>
</tr>
<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-8-mediumblue.svg">stroke-8-mediumblue.svg</a></td><td>2,118 (reverse)</td><td>100</td><td>3.24 sec</td><td>95%</td><td>0.39 sec</td><td>88%</td><td>88%</td>
</tr>
</table>

### CODE REVIEW

**Comment by oskay** [comment]
Neat! I was just starting to look at using the same R-tree from the previous PR as spatial index to improve the speed of a greedy search.

It's an interesting question as to what the right set of tradeoffs is on plot optimization. Ideally, we would pick a method that (typically) minimizes the total (plot optimization + plotting) time.  If optimizing is faster, but plotting takes longer, that won't necessarily be an improvement. 

As an aside on that topic, Paul Butler has a blog post that notes that TSP optimization past greedy/nearest-neighbor probably isn't a big win for plotting: https://nb.paulbutler.org/optimizing-plots-with-tsp-solver/

**Comment by migurski** [comment]
That’s a great post. Interesting that he proposes using an R-Tree. I was thinking about reusing the previous code, and decided not to because `reorder()` needs to cover all points including very distant ones in contrast to `connect_nearby_ends()` which is just trying to find local hops. The Hilbert curve is not dissimilar to an R-Tree, but has the nice property of putting everything on a one-dimensional line. We could probably use `rtree.py` to generate a similar ordering of inputs though it’d be a z-order curve.

**Comment by oskay** [comment]
I was looking at possibly trying a modified version of this approach: https://sigmodrecord.org/publications/sigmodRecord/9809/pdfs/290593.290596.pdf

**Comment by migurski** [comment]
I added total ordering to `rtree.py` and swapped out the Hilbert Curve in 63d0bd8. The results are probably just as good!

<table>
<tr>
<th>File</th><th>Paths</th><th><tt>CURVE_DISTANCE</tt></th><th>Time before #113</th><th>Distance savings before #113</th><th>Time after #113</th><th>Distance savings after #113</th><th>Time Improvement</th>
</tr>

<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-11-navy.svg">stroke-11-navy.svg</a></td><td>3,424</td><td>100</td><td>4.63 sec</td><td>90%</td><td>0.61 sec</td><td>88%</td><td>87%</td>
</tr>
<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-11-navy.svg">stroke-11-navy.svg</a></td><td>3,424 (reverse)</td><td>100</td><td>9.07 sec</td><td>96%</td><td>0.60 sec</td><td>92%</td><td>93%</td>
</tr>
<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-8-mediumblue.svg">stroke-8-mediumblue.svg</a></td><td>2,118</td><td>100</td><td>1.72 sec</td><td>88%</td><td>0.31 sec</td><td>87%</td><td>82%</td>
</tr>
<tr>
<td><a href="http://mike.teczno.com/img/axicli-examples-2021-12-19/stroke-8-mediumblue.svg">stroke-8-mediumblue.svg</a></td><td>2,118 (reverse)</td><td>100</td><td>3.24 sec</td><td>95%</td><td>0.44 sec</td><td>92%</td><td>86%</td>
</tr>
</table>

**Comment by oskay** [comment]
Wow; not bad!

**Comment by migurski** [comment]
> Ideally, we would pick a method that (typically) minimizes the total (plot optimization + plotting) time. If optimizing is faster, but plotting takes longer, that won't necessarily be an improvement.

All the test times above are on my fast laptop. When I’m actually plotting I run `axicli` from a Raspberry Pi Zero 2 W where these big loops can take much longer. Would it be useful for me to benchmark there as well for this PR?

**Comment by oskay** [comment]
> Would it be useful for me to benchmark there as well for this PR?

I'm not sure that it's necessary; this is pretty close to being an "unqualified" improvement. That said, adding one or two plot time estimates would provide better context.

**Comment by migurski** [comment]
Some sample estimate results run on my laptop:

<table>
<tr>
<th>Estimate</th><th>Estimate time before #113</th><th>Print time before #113</th><th>Estimate time after #113</th><th>Print time after #113</th>
</tr>
<tr>
<td><tt>axicli --preview -T stroke-11-navy.svg</tt><td>2.09 sec</td><td>0:42:44</td></td><td>1.77 sec</td><td>0:42:44</td>
</tr>
<tr>
<td><tt>axicli --preview -G1 -T stroke-11-navy.svg</tt></td><td>5.83 sec</td><td>0:32:45</td><td>2.36 sec</td><td>0:33:09</td>
</tr>
<tr>
<td><tt>axicli --preview -G2 -T stroke-11-navy.svg</tt></td><td>2.70 sec</td><td>0:16:17</td><td>1.72 sec</td><td>0:16:35</td>
</tr>
<tr>
<td><tt>axicli --preview  -T stroke-8-mediumblue.svg</tt></td><td>13 sec</td><td>3:18:47</td><td>13 sec</td><td>3:18:47</td>
</tr>
<tr>
<td><tt>axicli --preview -G1 -T stroke-8-mediumblue.svg</tt></td><td>226 sec</td><td>3:05:31</td><td>17 sec</td><td>3:07:05</td>
</tr>
<tr>
<td><tt>axicli --preview -G2 -T stroke-8-mediumblue.svg</tt></td><td>208 sec</td><td>2:13:42</td><td>17 sec</td><td>2:18:39</td>
</tr>

</table>

**Comment by oskay** [comment]
We're using "optimizing" in a couple ways here. 😆 

If I'm reading this right, this is a slightly longer total (computation + print time), on a fast computer, with this PR added -- on the last line, that's about five minutes longer plot time, but three minutes shorter computation time.

**Comment by migurski** [comment]
Good point, I’ve changed the headers to be less confusing. Your reading is right. I generally prefer to see the plot start more quickly and proceed more smoothly even if there’s a small time cost to prevent a dry pen tip. During the unpredictable pre-plotting time I scrape the pen tip with a post-it note to keep ink flowing, it’d be nice to not need to do that.

**Comment by oskay** [comment]
One of the things that I'm working on right now is a separate mode that outputs the optimized document, such that the optimization and plotting stages can be separated.

**Comment by migurski** [comment]
That would be amazing, I already do color separations before transferring files for plotting and it’d be nice to have them ready-to-spool directly to the AxiDraw.

**Comment by oskay** [comment]
It looks as though some intermediary performance can be achieved through a different choice of `CURVE_DISTANCE`.


Some sample estimate results run on my laptop,  with `CURVE_DISTANCE = 600`:
<table>
<tr>
<th>Estimate</th><th>Estimate time before #113</th><th>Print time before #113</th><th>Estimate time after #113</th><th>Print time after #113</th>
<tr>
<td><tt>axicli --preview  -T stroke-8-mediumblue.svg</tt></td><td>5.1 sec</td><td>3:18:47</td><td>5.1 sec</td><td>3:18:47</td>
</tr>
<tr>
<td><tt>axicli --preview -G1 -T stroke-8-mediumblue.svg</tt></td><td>1:11</td><td>3:05:31</td><td>11 sec</td><td>3:08:11</td>
</tr>
<tr>
<td><tt>axicli --preview -G2 -T stroke-8-mediumblue.svg</tt></td><td>1:12</td><td>2:13:42</td><td>11 sec</td><td>2:15:35</td>
</tr>

</table>

This saves about a minute in optimization, costs about two minutes in plot time. 

It may be better to consider a dynamic value of `CURVE_DISTANCE`, either based on the initial number of paths, or one that decreases with `len(spatial_index)`.  I've played with it a bit, and it looks like there are further tradeoffs available. However, in quick tests, I didn't see any see any choice that was unambiguously best

**Comment by migurski** [comment]
It makes sense that a higher `CURVE_DISTANCE` would have this effect. Maybe something like `min(1000, len(spatial_index)/5)` to scale with the path count and still have an upper bound?

**Comment by j2kun** [comment]
Sorry for the random drive-by comment, but I'm a mathematician/programmer interested in cataloguing some use cases of Hilbert curves in practical settings. Can you confirm from the above discussion that the Hilbert curve ordering for your R-tree is _not_ going to be considered part of this PR? (In place of the z-ordering or "Morton" encoding, as it were?)

(PS, I think AxiDraws are pretty cool and I've had my eye on getting one for a while now, so I will probably be benefitting from this optimization at some point!)

**Comment by oskay** [comment]
> Can you confirm from the above discussion that the Hilbert curve ordering for your T-tree is _not_ going to be considered part of this PR?

Not yet; sorry. I'm evaluating several approaches including some that do and do not include the Hilbert curve.

**Comment by oskay** [comment]
> It makes sense that a higher `CURVE_DISTANCE` would have this effect. Maybe something like `min(1000, len(spatial_index)/5)` to scale with the path count and still have an upper bound?

That's pretty close to what I was looking at.

**Comment by oskay** [comment]
Playing with this some more, I tried a different approach with a spatial index that didn't improve things much-- there are some further optimizations that may help, but it doesn't feel like the right direction.

Second, I tried using this branch (more or less, as-is), but adding a secondary stage of 2-opt local optimization. The 2-opt stage does decrease the plot time, but running it long enough to make up the difference between the result of the Hilbert curve versus nearest neighbor increases the processing time dramatically; it does not appear to be a good strategy.

Third, I tried rewriting the Hilbert curve branch for slightly better speed-- mostly just reducing `first_point`/`last_point` lookups and building the new tour order via index and only making the new path list at the end.  This reduced the computation time by about 30%. With that speed improvement and setting `CURVE_DISTANCE` as `max(int(len(spatial_index) / 4), 500)` -- I was able to "break even", which I will break down a bit further here:

Prior to any changes in this PR, I had:
```
axicli --preview -G2 -T stroke-8-mediumblue.svg
Estimated print time: 2:13:42 (Hours, minutes, seconds)
Pen-up travel distance: 11.25 m
This estimate took 1:12 (Minutes, seconds)
```

With that last set of changes (This branch but about 30% faster, with `CURVE_DISTANCE` ~ `(len(spatial_index) / 4)`), I can get:
```
axicli --preview -G2 -T stroke-8-mediumblue.svg
Estimated print time: 2:14:24 (Hours, minutes, seconds)
Pen-up travel distance: 12.42 m
This estimate took 28 Seconds
```
That's about 42 seconds longer plot than prior to changes, and 44 seconds shorter optimization, on my computer which is relatively fast.

If a computer takes 208 s (versus my 72 s) for the initial estimate, it would (with some hand waving) take about 81 seconds with the faster version here. That would result in a 127 s savings in computation, with 42 s longer plot time -- a more significant improvement.

This is not nearly as dramatic of a computation speedup as your initial PR here, but does become a more clear improvement-- about the same total (computation+print) time, but significantly less delay time before the plot starts.

I'll keep at this a bit; there are likely further gains to be found.

**Comment by migurski** [comment]
I appreciate your rigor on this! Thanks again for giving these contributions such serious consideration.

**Comment by oskay** [comment]
The big idea here is to use the Hilbert curve position as a proxy for nearness, which -- as the number bear out here -- can *very quickly* give a path somewhere roughly 95% as short as the exhaustive nearest neighbor search. (That last few percent though!)

The trouble with a space filling curve approach is that certain points that are very near each other in cartesian distance can be quite far away along the curve. As I noted a couple of days ago, we can get better plot times, by extending the length of the curve to check. But, by the time we get the "break even" between plotting and computation time, we're checking fully half of the Hilbert curve, which greatly diminishes the speed advantage.

After the three approaches that I mentioned above, I had a different idea. It's perhaps more rudimentary, but I tried a grid-based spatial index. It divides the document into an n×n array of cells that can be mapped to a 1D list. Each cell contains a list of the vertices that can be found in that cell.

To find the nearest vertex to a given point, we determine which cell the point is in. We then check every vertex in that cell and its (up to 8) nearest neighbor cells. The closest vertex within those cells is *in most cases* also the closest vertex globally. In a sense, the 9-cell neighborhood (with the initial point constrained to the center cell) acts like a very crude circular search region around the point.

The results seem quite promising:

```
axicli --preview -G2 -T stroke-8-mediumblue.svg
Estimated print time: 2:13:43 (Hours, minutes, seconds)
Pen-up travel distance: 11.36 m
This estimate took 11 Seconds
```

```
axicli --preview -G1 -T stroke-8-mediumblue.svg
Estimated print time: 3:05:30 (Hours, minutes, seconds)
Pen-up travel distance: 27.50 m
This estimate took 8.024 Seconds
```

I've put this test up in a branch, here:  https://github.com/evil-mad/axidraw/tree/grid_index
@migurski Would you be willing to take a look and see if this works well for you?

**Comment by j2kun** [comment]
The grid-based index above sounds like a quadtree, whose leaves are often indexed in the Hilbert curve order. Perhaps that could be an improvement over a regular grid?

**Comment by oskay** [comment]
> The grid-based index above sounds like a quadtree, whose leaves are often indexed in the Hilbert curve order. Perhaps that could be an improvement over a regular grid?

I'm afraid that it really is just a flat grid index, not a quadtree.

**Comment by migurski** [comment]
I’ll have a look at your proposed code. I’ve used flat grids like this in the past and they’ve worked very well when the row/column counts are chosen based on input data.

**Comment by migurski** [comment]
It looks pretty solid, thanks for sharing! I can’t think of any obvious changes I’d suggest.

**Comment by oskay** [comment]
Great, thanks!

And, *thank you* for your work on this. Your examples and PR were *very* helpful on getting to where we ended up on this. I sincerely appreciate it.

**Pull request closed without merging**
